= Language description

Your features may use the following step definitions (you may choose to use single or double quotes).
The logic of the particular step is also available as a method for the composition in the domain specific steps.


== Event-B

* Setup constants (optionally with the given constants constraints) and initialize the machine.
+
----
Given machine
----
+
----
Given machine with "«Formula»"
----
+
----
Given machine with
  """
    «Formula»
  """
----
+
Available as `setupConstantsInitialiseMachine(String formula)` method (parameter `formula` is optional).


* Fire the given event (optionally with the given parameters constraints).
+
----
When fire event "«Event-Name»"
----
+
----
When fire event "«Event-Name»" with "«Formula»"
----
+
Available as `fireEvent(String eventName, String formula)` method (parameter `formula` is optional).


* Fire the given event multiple times with the given parameters constraints (one data table row for each invocation).
+
----
When fire event "«Event-Name»" with
    | name-1 | name-2 | ... |
    | val-11 | val-12 | ... |
    | val-21 | val-22 | ... |
----
+
Available as `fireEvents(String eventName, List<Map<String, String>> maps)` method.


* Check if the given event (optionally with the given parameters constraints) is enabled.
+
----
Then event "«Event-Name»" is enabled
----
+
----
Then event "«Event-Name»" with "«Formula»" is enabled
----
+
Available as `isEventEnabled(String eventName, String formula)` method (parameter `formula` is optional).


* Check if the given event (optionally with the given parameters constraints) is disabled.
+
----
Then event "«Event-Name»" is disabled
----
+
----
Then event "«Event-Name»" with "«Formula»" is disabled
----
+
Available as `isEventDisabled(String eventName, String formula)` method (parameter `formula` is optional).


* Check if the given formula evaluates to the given value.
+
----
Then formula "«Formula»" is TRUE
----
+
----
Then formula "«Formula»" is FALSE
----
+
Available as `isFormula(String formula, String value)` method.


== iUML-B State Machines (both enumeration and variables translation)

The state machine identification is either the plain state machine name (e.g. `StateMachine`) or for the lifted state machine the state machine name followed by the instance, separated by the colon (e.g. `StateMachine:Instance`).

* Preset the given state machine for subsequent steps.
+
----
Given state machine "«State-Machine»"
----

* Trigger the given transition (optionally with the given parameters constraints) of the preset or given state machine.
+
----
When trigger transition "«Trans-Name»"
----
+
----
When trigger transition "«Trans-Name»" with "«Formula»"
----
+
----
When trigger transition "«Trans-Name»" for state machine "«State-Machine»"
----
+
----
When trigger transition "«Trans-Name»" with "«Formula»" for state machine "«State-Machine»"
----
+
Available as `triggerTransition(String transName, String smId, String formula)` method (parameters `smId` and `formula` are optional).


* Check, if the given transition (optionally with the given parameters constraints) of the preset or given state machine is enabled.
+
----
Then transition "«Trans-Name»" is enabled
----
+
----
Then transition "«Trans-Name»" with "«Formula»" is enabled
----
+
----
Then transition "«Trans-Name»" is enabled for state machine "«State-Machine»"
----
+
----
Then transition "«Trans-Name»" with "«Formula»" is enabled for state machine "«State-Machine»"
----
+
Available as `isTransitionEnabled(String transName, String smId, String formula)` method (parameters `smId` and `formula` are optional).


* Check, if the given transition (optionally with the given parameters constraints) of the preset or given state machine is disabled.
+
----
Then transition "«Trans-Name»" is disabled
----
+
----
Then transition "«Trans-Name»" with "«Formula»" is disabled
----
+
----
Then transition "«Trans-Name»" is disabled for state machine "«State-Machine»"
----
+
----
Then transition "«Trans-Name»" with "«Formula»" is disabled for state machine "«State-Machine»"
----
+
Available as `isTransitionDisabled(String transName, String smId, String formula)` method (parameters `smId` and `formula` are optional).


* Check, if the preset or given state machine is or is not in the given state.
+
----
Then is in state "«State»"
----
+
----
Then is not in state "«State»"
----
+
----
Then state machine "«State-Machine»" is in state "«State»"
----
+
----
Then state machine "«State-Machine»" is not in state "«State»"
----
+
Available as `isInState(String smId, String state, boolean not)` method (parameters `smId` and `not` are optional).


== iUML-B Class Diagrams

The class instance identification is the class name followed by the instance, separated by the colon (e.g. `ClassName:Instance`).

* Preset the given class instance for subsequent steps.
+
----
`Given class instance "«Class»"`
----


* Call the given method (optionally with the given parameters constraints) of the preset or given classs instance.
+
----
When call method "«Method-Name»"
----
+
----
When call method "«Method-Name»" with "«Formula»"
----
+
----
When call method "«Method-Name»" for class instance "«Class»"
----
+
----
When call method "«Method-Name»" with "«Formula»" for class instance "«Class»"
----
+
Available as `callMethod(methodName, classId, formula)` method (parameters `classId` and `formula` are optional)


* Check, if the given method (optionally with the given parameters constraints) of the preset or given classs instance is enabled.
+
----
Then method "«Method-Name»" is enabled
----
+
----
Then method "«Method-Name»" with "«Formula»" is enabled
----
+
----
Then method "«Method-Name»" is enabled for class instance "«Class»"
----
+
----
Then method "«Method-Name»" with "«Formula»" is enabled for class instance "«Class»"
----
+
Available as `isMethodEnabled(methodName, classId, formula)` method (parameters `classId` and `formula` are optional).


* Check, if the given method (optionally with the given parameters constraints) of the preset or given classs instance is disabled.
+
----
Then method "«Method-Name»" is disabled
----
+
----
Then method "«Method-Name»" with "«Formula»" is disabled
----
+
----
Then method "«Method-Name»" is disabled for class instance "«Class»"
----
+
----
Then method "«Method-Name»" with "«Formula»" is disabled for class instance "«Class»"
----
+
Available as `isMethodDisabled(methodName, classId, formula)` method (parameters `classId` and `formula` are optional).


* Check, if the given attribute of the preset or given class instance has or has not the given value.
+
----
Then attribute "«Attr-Name»" is "«Value»"
----
+
----
Then attribute "«Attr-Name»" is not "«Value»"
----
+
----
Then attribute "«Attr-Name»" of class instance "«Class»" is "«Value»"
----
+
----
Then attribute "«Attr-Name»" of class instance "«Class»" is not "«Value»"
----
+
Available as `isAttribute(String classId, String attrName, String value, boolean not)` method (parameters `classId` and `not` are optional).


== Restrictions

* Only class diagrams within Event-B machines (not within Event-B contexts) are considered
* An association can be referenced as an attribute.
* A lifted state machine and a corresponding class must have the same self names.

